import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [arr, setArr] = useState([]);
  const [sec, setSec] = useState([]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.calcContainer}>
          <div className={styles.calcScreen}>
            <div className={styles.calcScreenTheme}>Theme Switch</div>
            <div className={styles.calcScreenSecondary}>
              {sec.map((curr) => curr)}
            </div>
            <div className={styles.calcScreenPrimary}>
              {arr.map((curr) => curr)}
            </div>
          </div>
          <div className={styles.calcKeypad}>
            <div className={styles.keysContainer}>
              <div className={styles.leftKeysContainer}>
                <div className={styles.topKeys}>
                  <button className={styles.btnSize}>AC</button>
                  <button className={styles.btnSize}>C</button>
                  <button className={styles.btnSize}>%</button>
                </div>
                <div className={styles.downKeys}>
                  <div className={styles.downKeysRow1}>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 1])}
                    >
                      1
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 2])}
                    >
                      2
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 3])}
                    >
                      3
                    </button>
                  </div>
                  <div className={styles.downKeysRow2}>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 4])}
                    >
                      4
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 5])}
                    >
                      5
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 6])}
                    >
                      6
                    </button>
                  </div>
                  <div className={styles.downKeysRow3}>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 7])}
                    >
                      7
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 8])}
                    >
                      8
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 9])}
                    >
                      9
                    </button>
                  </div>
                  <div className={styles.downKeysRow4}>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, "."])}
                    >
                      .
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, 0])}
                    >
                      0
                    </button>
                    <button
                      className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                      onClick={() => setArr(() => [...arr, "00"])}
                    >
                      00
                    </button>
                  </div>

                  {/* <button className={styles.btnSize}>+</button>
                  <button className={styles.btnSize}>=</button>
                  <button className={styles.btnSize}>/</button>
                  <button className={styles.btnSize}>x</button>
                  <button className={styles.btnSize}>-</button>
                  <button className={styles.btnSize}>+</button>
                  <button className={styles.btnSize}>=</button>
                  <button className={styles.btnSize}>/</button>
                  <button className={styles.btnSize}>x</button> */}
                </div>
              </div>
              <div className={styles.rightKeysContainer}>
                <button
                  className={styles.btnSize}
                  onClick={() => setArr(() => [...arr, "÷"])}
                >
                  ÷
                </button>
                <button
                  className={styles.btnSize}
                  onClick={() => setArr(() => [...arr, "x"])}
                >
                  x
                </button>
                <button
                  className={styles.btnSize}
                  onClick={() => setArr(() => [...arr, "-"])}
                >
                  -
                </button>
                <button
                  className={styles.btnSize}
                  onClick={() => setArr(() => [...arr, "+"])}
                >
                  +
                </button>
                <button
                  className={`${styles.btnSize} ${styles.downBtnRowColor}`}
                  onClick={() => setSec(() => [...arr])}
                >
                  =
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Developed by Dacooleric</footer>
    </div>
  );
}
